version: '3.8'

services:
  scanner:
    build: .
    container_name: imageScanner
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - db-cache:/root/.cache/trivy
    restart: unless-stopped

volumes:
  db-cache:
    name: db-cache
